// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoIngenieria.Repository;

#nullable disable

namespace ProyectoIngenieria.Data.Migrations
{
    [DbContext(typeof(ProyectoIngenieriaContext))]
    [Migration("20250622213752_AddCampoLeidaANotificacion")]
    partial class AddCampoLeidaANotificacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.CatalogoMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("CATALOGO_MANTENIMIENTO_pk");

                    b.ToTable("CATALOGO_MANTENIMIENTO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.CatalogoRepuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioEstimado")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Precio_Estimado");

                    b.HasKey("Id")
                        .HasName("CATALOGO_REPUESTO_pk");

                    b.ToTable("CATALOGO_REPUESTO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.DocumentoOperador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OperadorCedula")
                        .HasColumnType("int")
                        .HasColumnName("OPERADOR_Cedula");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("DOCUMENTO_OPERADOR_pk");

                    b.HasIndex("OperadorCedula");

                    b.ToTable("DOCUMENTO_OPERADOR", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.DocumentoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICULO_ID");

                    b.HasKey("Id")
                        .HasName("DOCUMENTO_VEHICULO_pk");

                    b.HasIndex("VehiculoId");

                    b.ToTable("DOCUMENTO_VEHICULO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("EMPRESA_pk");

                    b.ToTable("EMPRESA", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.HorasTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal>("HorometroFinal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Horometro_Final");

                    b.Property<decimal>("HorometroInicial")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Horometro_Inicial");

                    b.Property<int>("LugarTrabajoId")
                        .HasColumnType("int")
                        .HasColumnName("LUGAR_TRABAJO_ID");

                    b.Property<decimal>("PrecioHora")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Precio_Hora");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("PROYECTO_ID");

                    b.Property<int>("TipoTrabajoId")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_TRABAJO_ID");

                    b.Property<decimal>("TotalGanancia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Total_Ganancia");

                    b.Property<decimal>("TotalHoras")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Total_Horas");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICULO_ID");

                    b.HasKey("Id")
                        .HasName("HORAS_TRABAJO_pk");

                    b.HasIndex("LugarTrabajoId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TipoTrabajoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("HORAS_TRABAJO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.LugarTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("LUGAR_TRABAJO_pk");

                    b.ToTable("LUGAR_TRABAJO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre_Marca");

                    b.HasKey("Id")
                        .HasName("MARCA_pk");

                    b.ToTable("MARCA", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICULO_ID");

                    b.HasKey("Id")
                        .HasName("NOTIFICACION_pk");

                    b.HasIndex("VehiculoId");

                    b.ToTable("NOTIFICACION", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Operador", b =>
                {
                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TipoColaborador")
                        .IsRequired()
                        .HasMaxLength(39)
                        .HasColumnType("nvarchar(39)")
                        .HasColumnName("Tipo_Colaborador");

                    b.HasKey("Cedula")
                        .HasName("OPERADOR_pk");

                    b.ToTable("OPERADOR", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Inicio");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Proyecto");

                    b.HasKey("Id")
                        .HasName("PROYECTO_pk");

                    b.ToTable("PROYECTO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.RegistroCombustible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FechaCompra")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Compra");

                    b.Property<decimal>("LitrosComprados")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Litros_Comprados");

                    b.Property<decimal>("PrecioLitro")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Precio_Litro");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Total_Pagado");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICULO_ID");

                    b.HasKey("Id")
                        .HasName("REGISTRO_COMBUSTIBLE_pk");

                    b.HasIndex("VehiculoId");

                    b.ToTable("REGISTRO_COMBUSTIBLE", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.RegistroMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogoMantenimientoId")
                        .HasColumnType("int")
                        .HasColumnName("CATALOGO_MANTENIMIENTO_ID");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("OperadorCedula")
                        .HasColumnType("int")
                        .HasColumnName("OPERADOR_Cedula");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICULO_ID");

                    b.HasKey("Id")
                        .HasName("REGISTRO_MANTENIMIENTO_pk");

                    b.HasIndex("CatalogoMantenimientoId");

                    b.HasIndex("OperadorCedula");

                    b.HasIndex("VehiculoId");

                    b.ToTable("REGISTRO_MANTENIMIENTO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.RegistroOperadore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("OperadorCedula")
                        .HasColumnType("int")
                        .HasColumnName("OPERADOR_Cedula");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICULO_ID");

                    b.HasKey("Id")
                        .HasName("REGISTRO_OPERADORES_pk");

                    b.HasIndex("OperadorCedula");

                    b.HasIndex("VehiculoId");

                    b.ToTable("REGISTRO_OPERADORES", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FechaReporte")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Reporte");

                    b.Property<decimal>("GastoCombustible")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Gasto_Combustible");

                    b.Property<decimal>("GastoMantenimiento")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Gasto_Mantenimiento");

                    b.Property<decimal>("IngresoTotal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Ingreso_Total");

                    b.Property<DateOnly>("PeriodoFin")
                        .HasColumnType("date")
                        .HasColumnName("Periodo_Fin");

                    b.Property<DateOnly>("PeriodoInicio")
                        .HasColumnType("date")
                        .HasColumnName("Periodo_Inicio");

                    b.Property<decimal>("TotalHoras")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Total_Horas");

                    b.Property<decimal>("Utilidad")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICULO_ID");

                    b.HasKey("Id")
                        .HasName("REPORTE_pk");

                    b.HasIndex("VehiculoId");

                    b.ToTable("REPORTE", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.RepuestosMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogoRepuestoId")
                        .HasColumnType("int")
                        .HasColumnName("CATALOGO_REPUESTO_ID");

                    b.Property<int>("RegistroMantenimientoId")
                        .HasColumnType("int")
                        .HasColumnName("REGISTRO_MANTENIMIENTO_ID");

                    b.HasKey("Id")
                        .HasName("REPUESTOS_MANTENIMIENTO_pk");

                    b.HasIndex("CatalogoRepuestoId");

                    b.HasIndex("RegistroMantenimientoId");

                    b.ToTable("REPUESTOS_MANTENIMIENTO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.TipoTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("TIPO_TRABAJO_pk");

                    b.ToTable("TIPO_TRABAJO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.TipoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("TIPO_VEHICULO_pk");

                    b.ToTable("TIPO_VEHICULO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("MARCA_ID");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_VEHICULO_ID");

                    b.HasKey("Id")
                        .HasName("VEHICULO_pk");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("VEHICULO", (string)null);
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.DocumentoOperador", b =>
                {
                    b.HasOne("ProyectoIngenieria.Models.Operador", "OperadorCedulaNavigation")
                        .WithMany("DocumentoOperadors")
                        .HasForeignKey("OperadorCedula")
                        .IsRequired()
                        .HasConstraintName("DOCUMENTO_OPERADOR_OPERADOR");

                    b.Navigation("OperadorCedulaNavigation");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.DocumentoVehiculo", b =>
                {
                    b.HasOne("ProyectoIngenieria.Models.Vehiculo", "Vehiculo")
                        .WithMany("DocumentoVehiculos")
                        .HasForeignKey("VehiculoId")
                        .IsRequired()
                        .HasConstraintName("DOCUMENTO_MAQUINA");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.HorasTrabajo", b =>
                {
                    b.HasOne("ProyectoIngenieria.Models.LugarTrabajo", "LugarTrabajo")
                        .WithMany("HorasTrabajos")
                        .HasForeignKey("LugarTrabajoId")
                        .IsRequired()
                        .HasConstraintName("HORAS_TRABAJO_LUGAR_TRABAJO");

                    b.HasOne("ProyectoIngenieria.Models.Proyecto", "Proyecto")
                        .WithMany("HorasTrabajos")
                        .HasForeignKey("ProyectoId")
                        .IsRequired()
                        .HasConstraintName("HORAS_TRABAJO_PROYECTO");

                    b.HasOne("ProyectoIngenieria.Models.TipoTrabajo", "TipoTrabajo")
                        .WithMany("HorasTrabajos")
                        .HasForeignKey("TipoTrabajoId")
                        .IsRequired()
                        .HasConstraintName("HORAS_TRABAJO_TIPO_TRABAJO");

                    b.HasOne("ProyectoIngenieria.Models.Vehiculo", "Vehiculo")
                        .WithMany("HorasTrabajos")
                        .HasForeignKey("VehiculoId")
                        .IsRequired()
                        .HasConstraintName("HORAS_TRABAJO_MAQUINA");

                    b.Navigation("LugarTrabajo");

                    b.Navigation("Proyecto");

                    b.Navigation("TipoTrabajo");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Notificacion", b =>
                {
                    b.HasOne("ProyectoIngenieria.Models.Vehiculo", "Vehiculo")
                        .WithMany("Notificacions")
                        .HasForeignKey("VehiculoId")
                        .IsRequired()
                        .HasConstraintName("NOTIFICACION_MAQUINA");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.RegistroCombustible", b =>
                {
                    b.HasOne("ProyectoIngenieria.Models.Vehiculo", "Vehiculo")
                        .WithMany("RegistroCombustibles")
                        .HasForeignKey("VehiculoId")
                        .IsRequired()
                        .HasConstraintName("REGISTRO_COMBUSTIBLE_MAQUINA");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.RegistroMantenimiento", b =>
                {
                    b.HasOne("ProyectoIngenieria.Models.CatalogoMantenimiento", "CatalogoMantenimiento")
                        .WithMany("RegistroMantenimientos")
                        .HasForeignKey("CatalogoMantenimientoId")
                        .IsRequired()
                        .HasConstraintName("REGISTRO_MANTENIMIENTO_CATALOGO_MANTENIMIENTO");

                    b.HasOne("ProyectoIngenieria.Models.Operador", "OperadorCedulaNavigation")
                        .WithMany("RegistroMantenimientos")
                        .HasForeignKey("OperadorCedula")
                        .IsRequired()
                        .HasConstraintName("REGISTRO_MANTENIMIENTO_OPERADOR");

                    b.HasOne("ProyectoIngenieria.Models.Vehiculo", "Vehiculo")
                        .WithMany("RegistroMantenimientos")
                        .HasForeignKey("VehiculoId")
                        .IsRequired()
                        .HasConstraintName("REGISTRO_MANTENIMIENTO_MAQUINA");

                    b.Navigation("CatalogoMantenimiento");

                    b.Navigation("OperadorCedulaNavigation");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.RegistroOperadore", b =>
                {
                    b.HasOne("ProyectoIngenieria.Models.Operador", "OperadorCedulaNavigation")
                        .WithMany("RegistroOperadores")
                        .HasForeignKey("OperadorCedula")
                        .IsRequired()
                        .HasConstraintName("REGISTRO_OPERADORES_OPERADOR");

                    b.HasOne("ProyectoIngenieria.Models.Vehiculo", "Vehiculo")
                        .WithMany("RegistroOperadores")
                        .HasForeignKey("VehiculoId")
                        .IsRequired()
                        .HasConstraintName("REGISTRO_OPERADORES_VEHICULO");

                    b.Navigation("OperadorCedulaNavigation");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Reporte", b =>
                {
                    b.HasOne("ProyectoIngenieria.Models.Vehiculo", "Vehiculo")
                        .WithMany("Reportes")
                        .HasForeignKey("VehiculoId")
                        .IsRequired()
                        .HasConstraintName("REPORTE_VEHICULO");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.RepuestosMantenimiento", b =>
                {
                    b.HasOne("ProyectoIngenieria.Models.CatalogoRepuesto", "CatalogoRepuesto")
                        .WithMany("RepuestosMantenimientos")
                        .HasForeignKey("CatalogoRepuestoId")
                        .IsRequired()
                        .HasConstraintName("REPUESTOS_MANTENIMIENTO_CATALOGO_REPUESTO");

                    b.HasOne("ProyectoIngenieria.Models.RegistroMantenimiento", "RegistroMantenimiento")
                        .WithMany("RepuestosMantenimientos")
                        .HasForeignKey("RegistroMantenimientoId")
                        .IsRequired()
                        .HasConstraintName("REPUESTOS_MANTENIMIENTO_REGISTRO_MANTENIMIENTO");

                    b.Navigation("CatalogoRepuesto");

                    b.Navigation("RegistroMantenimiento");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Vehiculo", b =>
                {
                    b.HasOne("ProyectoIngenieria.Models.Empresa", "Empresa")
                        .WithMany("Vehiculos")
                        .HasForeignKey("EmpresaId")
                        .IsRequired()
                        .HasConstraintName("MAQUINA_EMPRESA");

                    b.HasOne("ProyectoIngenieria.Models.Marca", "Marca")
                        .WithMany("Vehiculos")
                        .HasForeignKey("MarcaId")
                        .IsRequired()
                        .HasConstraintName("VEHICULO_MARCA");

                    b.HasOne("ProyectoIngenieria.Models.TipoVehiculo", "TipoVehiculo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("TipoVehiculoId")
                        .IsRequired()
                        .HasConstraintName("VEHICULO_TIPO_VEHICULO");

                    b.Navigation("Empresa");

                    b.Navigation("Marca");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.CatalogoMantenimiento", b =>
                {
                    b.Navigation("RegistroMantenimientos");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.CatalogoRepuesto", b =>
                {
                    b.Navigation("RepuestosMantenimientos");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Empresa", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.LugarTrabajo", b =>
                {
                    b.Navigation("HorasTrabajos");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Marca", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Operador", b =>
                {
                    b.Navigation("DocumentoOperadors");

                    b.Navigation("RegistroMantenimientos");

                    b.Navigation("RegistroOperadores");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Proyecto", b =>
                {
                    b.Navigation("HorasTrabajos");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.RegistroMantenimiento", b =>
                {
                    b.Navigation("RepuestosMantenimientos");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.TipoTrabajo", b =>
                {
                    b.Navigation("HorasTrabajos");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.TipoVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("ProyectoIngenieria.Models.Vehiculo", b =>
                {
                    b.Navigation("DocumentoVehiculos");

                    b.Navigation("HorasTrabajos");

                    b.Navigation("Notificacions");

                    b.Navigation("RegistroCombustibles");

                    b.Navigation("RegistroMantenimientos");

                    b.Navigation("RegistroOperadores");

                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
